# Generated by Django 3.2 on 2021-04-07 18:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0002_auto_20210407_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 18, 4, 23, 231671, tzinfo=utc), verbose_name='Renewed Date'),
        ),
    ]
