# Generated by Django 3.2 on 2021-04-07 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0004_alter_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 18, 8, 54, 700814, tzinfo=utc), verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 18, 8, 54, 700790, tzinfo=utc), verbose_name='Renewed Date'),
        ),
    ]
