# Generated by Django 3.2 on 2021-04-07 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0005_auto_20210407_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Renewed Date'),
        ),
    ]
