# Generated by Django 3.2 on 2021-04-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0010_auto_20210408_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Member'},
        ),
    ]
